from pathlib import Path

import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st
from plotly.subplots import make_subplots


PROJECT_ROOT = Path(__file__).resolve().parents[1]
CSV_DIR = PROJECT_ROOT / "outputs" / "csv"

COLOR_TEXT = "#1F2937"
COLOR_MUTED = "#667085"
COLOR_BORDER = "#E4E7EC"
COLOR_PAGE = "#F6F8FB"
COLOR_CARD = "#FFFFFF"
COLOR_TEAL = "#247C7A"
COLOR_NAVY = "#24476F"
COLOR_BLUE = "#4C78A8"
COLOR_ORANGE = "#B76E2B"
COLOR_ROSE = "#B45F7A"
COLOR_GREEN = "#4A8F6B"

FEE_RATE_PROXY = 0.00025

px.defaults.template = "plotly_white"


COPY = {
    "English": {
        "language": "Language",
        "app_subtitle": "A retention workspace for FX product, growth, and CRM teams.",
        "who_for": "Built for Product Managers, Growth Marketers, and CRM teams",
        "nav": "Navigation",
        "pages": [
            "Business Overview",
            "Product Performance",
            "Target Users",
            "Segment Explorer",
            "Campaign Simulator",
            "Export Audience",
            "Prediction Quality",
        ],
        "page_subtitles": {
            "Business Overview": "Executive view of retention opportunity, audience quality, and campaign-ready segments.",
            "Product Performance": "Product analytics dashboard for onboarding, activation, feature adoption, retention, and FX context.",
            "Target Users": "Choose a business goal, select an audience, review the recommendation, and create a campaign list.",
            "Segment Explorer": "Investigate user-level predictions and filter the audience for CRM planning.",
            "Campaign Simulator": "Estimate how many repeat users, transaction volume, and fee proxy a campaign may add.",
            "Export Audience": "Prepare a CRM-ready target list with campaign context and selected user fields.",
            "Prediction Quality": "Model trust page for performance, prediction signals, and data caveats.",
        },
        "kpis": {
            "users_scored": ("Users scored", "Number of users scored by the repeat prediction model."),
            "avg_repeat": ("Avg repeat likelihood", "Average probability that scored users will repeat exchange activity in the next 30 days."),
            "expected_repeat": ("Expected repeat users", "Estimated number of users likely to make another exchange, based on prediction scores."),
            "priority_users": ("Priority users", "Users in segments that may need retention action or reliability support."),
            "target_audience": ("Target audience", "Users selected by the current segment and threshold filters."),
            "baseline_repeat": ("Baseline repeat users", "Expected repeat users before any campaign uplift is applied."),
            "incremental_repeat": ("Incremental repeat users", "Additional repeat users estimated from the campaign uplift assumption."),
            "incremental_volume": ("Estimated incremental volume", "Estimated extra transaction volume from incremental repeat users."),
            "recent_volume": ("Recent segment volume", "Total transaction volume generated by the selected users in the last 90 days."),
            "fee_proxy": ("Fee proxy impact", "Estimated fee opportunity using a simplified FX fee-rate assumption."),
            "high_value_at_risk": ("High-value at-risk users", "Users with meaningful recent volume but lower predicted repeat likelihood."),
            "recent_failed_rate": ("Recent failed transaction rate", "Share of recent transaction attempts that failed in the last 90 days."),
        },
        "goals": {
            "Increase repeat exchange": "Increase repeat exchange",
            "Promote rate-alert adoption": "Promote rate-alert adoption",
            "Promote target-rate order": "Promote target-rate order",
            "Reactivate low-probability users": "Reactivate low-probability users",
            "Protect high-value users": "Protect high-value users",
        },
        "goal_actions": {
            "Increase repeat exchange": "Send lifecycle nudges with recent FX movement, saved beneficiaries, and a one-tap repeat exchange CTA.",
            "Promote rate-alert adoption": "Prompt users to create rate alerts for their preferred currency pair.",
            "Promote target-rate order": "Educate users about target-rate orders with a pre-filled setup path.",
            "Reactivate low-probability users": "Run reactivation education with trust, pricing clarity, and first-step guidance.",
            "Protect high-value users": "Prioritize high-value users with concierge support and reliability reassurance.",
        },
        "segments": {
            "All users": "All users",
            "Low repeat probability users": "Low repeat likelihood users",
            "Medium repeat probability users": "Medium repeat likelihood users",
            "High repeat probability users": "High repeat likelihood users",
            "High-value at-risk users": "High-value at-risk users",
            "No recent transaction users": "No recent transaction users",
            "High failed-ratio users": "High failed transaction users",
        },
        "segment_help": "Audience group created from prediction score, recent activity, value, and transaction failure behavior.",
        "threshold_help": "Minimum repeat likelihood required for a user to enter the selected audience.",
        "uplift_help": "Assumed percentage improvement in repeat likelihood after the campaign.",
        "download_targets": "Download target users",
        "download_filtered": "Download filtered users",
        "download_export": "Download CRM audience",
        "campaign_name": "Campaign name",
        "campaign_notes": "Campaign notes",
        "selected_fields": "Fields to include",
        "empty_selection": "No users selected. Lower the threshold or choose a broader segment.",
        "prediction_plain": "The prediction model is used in Target Users, Segment Explorer, and Campaign Simulator. The technical quality checks are kept here so non-technical users can focus on actions first.",
    },
    "Korean": {
        "language": "언어",
        "app_subtitle": "FX 제품, 그로스, CRM 팀을 위한 리텐션 업무 공간입니다.",
        "who_for": "프로덕트 매니저, 그로스 마케터, CRM 팀을 위해 설계되었습니다",
        "nav": "탐색",
        "pages": [
            "비즈니스 개요",
            "제품 성과",
            "타깃 사용자",
            "세그먼트 탐색",
            "캠페인 시뮬레이터",
            "오디언스 내보내기",
            "예측 품질",
        ],
        "page_subtitles": {
            "Business Overview": "리텐션 기회, 오디언스 품질, 캠페인 가능 세그먼트를 한눈에 보는 경영진용 화면입니다.",
            "Product Performance": "온보딩, 활성화, 기능 채택, 리텐션, FX 시장 맥락을 보는 제품 분석 대시보드입니다.",
            "Target Users": "비즈니스 목표를 선택하고, 타깃 오디언스를 정한 뒤, 추천 액션과 캠페인 리스트를 만듭니다.",
            "Segment Explorer": "사용자별 예측 결과를 탐색하고 CRM 기획을 위한 오디언스를 필터링합니다.",
            "Campaign Simulator": "캠페인이 만들 수 있는 추가 재거래 사용자, 거래금액, 수수료 기회를 추정합니다.",
            "Export Audience": "캠페인 맥락과 사용자 필드를 포함한 CRM용 타깃 리스트를 준비합니다.",
            "Prediction Quality": "모델 성능, 예측 신호, 데이터 한계를 확인하는 신뢰도 점검 화면입니다.",
        },
        "kpis": {
            "users_scored": ("스코어링 사용자", "재거래 예측 모델이 점수를 계산한 사용자 수입니다."),
            "avg_repeat": ("평균 재거래 가능성", "향후 30일 안에 다시 환전할 가능성의 평균값입니다."),
            "expected_repeat": ("예상 재거래 사용자", "예측 점수를 기반으로 다시 환전할 것으로 예상되는 사용자 수입니다."),
            "priority_users": ("우선 관리 사용자", "리텐션 액션 또는 안정성 메시지가 필요할 수 있는 사용자입니다."),
            "target_audience": ("타깃 오디언스", "현재 세그먼트와 기준값 필터로 선택된 사용자입니다."),
            "baseline_repeat": ("기준선 재거래 사용자", "캠페인 효과를 적용하기 전 예상 재거래 사용자 수입니다."),
            "incremental_repeat": ("추가 재거래 사용자", "캠페인 효과 가정으로 추가될 수 있는 재거래 사용자 수입니다."),
            "incremental_volume": ("예상 추가 거래금액", "추가 재거래 사용자로부터 발생할 수 있는 추가 거래금액입니다."),
            "recent_volume": ("최근 세그먼트 거래금액", "선택된 사용자가 최근 90일 동안 만든 총 거래금액입니다."),
            "fee_proxy": ("수수료 기회 추정", "단순화한 FX 수수료율을 적용한 수수료 기회 추정치입니다."),
            "high_value_at_risk": ("고가치 이탈위험 사용자", "최근 거래금액은 크지만 재거래 가능성이 낮은 사용자입니다."),
            "recent_failed_rate": ("최근 거래 실패율", "최근 90일 거래 시도 중 실패한 비율입니다."),
        },
        "goals": {
            "Increase repeat exchange": "재거래 증가",
            "Promote rate-alert adoption": "환율 알림 사용 유도",
            "Promote target-rate order": "목표 환율 주문 유도",
            "Reactivate low-probability users": "낮은 가능성 사용자 재활성화",
            "Protect high-value users": "고가치 사용자 보호",
        },
        "goal_actions": {
            "Increase repeat exchange": "최근 FX 변동, 저장된 수취인, 원탭 재환전 CTA를 활용한 라이프사이클 메시지를 보냅니다.",
            "Promote rate-alert adoption": "사용자가 선호 통화쌍에 환율 알림을 만들도록 유도합니다.",
            "Promote target-rate order": "목표 환율 주문을 쉽게 이해하고 설정할 수 있는 경로를 제공합니다.",
            "Reactivate low-probability users": "신뢰, 가격 투명성, 첫 단계 안내를 중심으로 재활성화 캠페인을 운영합니다.",
            "Protect high-value users": "고가치 사용자에게 우선 지원과 안정성 메시지를 제공합니다.",
        },
        "segments": {
            "All users": "전체 사용자",
            "Low repeat probability users": "낮은 재거래 가능성 사용자",
            "Medium repeat probability users": "중간 재거래 가능성 사용자",
            "High repeat probability users": "높은 재거래 가능성 사용자",
            "High-value at-risk users": "고가치 이탈위험 사용자",
            "No recent transaction users": "최근 거래 없음 사용자",
            "High failed-ratio users": "거래 실패율 높은 사용자",
        },
        "segment_help": "예측 점수, 최근 활동, 사용자 가치, 거래 실패 행동을 바탕으로 만든 오디언스 그룹입니다.",
        "threshold_help": "선택한 오디언스에 포함되기 위해 필요한 최소 재거래 가능성입니다.",
        "uplift_help": "캠페인 이후 재거래 가능성이 얼마나 개선될지에 대한 가정입니다.",
        "download_targets": "타깃 사용자 다운로드",
        "download_filtered": "필터링 사용자 다운로드",
        "download_export": "CRM 오디언스 다운로드",
        "campaign_name": "캠페인 이름",
        "campaign_notes": "캠페인 메모",
        "selected_fields": "포함할 필드",
        "empty_selection": "선택된 사용자가 없습니다. 기준값을 낮추거나 더 넓은 세그먼트를 선택하세요.",
        "prediction_plain": "예측 모델은 타깃 사용자, 세그먼트 탐색, 캠페인 시뮬레이터에서 사용됩니다. 기술적인 품질 점검은 이 화면에 모아 비기술 사용자가 먼저 액션에 집중할 수 있게 했습니다.",
    },
}

PAGE_KEYS = {
    "Business Overview": "Business Overview",
    "Product Performance": "Product Performance",
    "Target Users": "Target Users",
    "Segment Explorer": "Segment Explorer",
    "Campaign Simulator": "Campaign Simulator",
    "Export Audience": "Export Audience",
    "Prediction Quality": "Prediction Quality",
    "비즈니스 개요": "Business Overview",
    "제품 성과": "Product Performance",
    "타깃 사용자": "Target Users",
    "세그먼트 탐색": "Segment Explorer",
    "캠페인 시뮬레이터": "Campaign Simulator",
    "오디언스 내보내기": "Export Audience",
    "예측 품질": "Prediction Quality",
}

FIELD_LABELS = {
    "user_id": "User ID",
    "observation_date": "Score date",
    "repeat_probability": "Repeat likelihood",
    "risk_segment": "Segment",
    "recommended_action": "Recommended action",
    "recommendation_reason": "Reason",
    "recency_days": "Days since last transaction",
    "transactions_90d": "Recent transactions",
    "transactions_all": "Lifetime transactions",
    "total_volume_90d": "Recent volume",
    "estimated_fee_proxy_90d": "Recent fee proxy",
    "failed_ratio_90d": "Recent failed transaction rate",
    "value_segment": "Value segment",
    "acquisition_channel": "Acquisition channel",
    "target_rate_user_flag": "Uses target-rate order",
    "rate_alert_user_flag": "Uses rate alert",
}

BASE_EXPORT_FIELDS = [
    "user_id",
    "observation_date",
    "repeat_probability",
    "risk_segment",
    "recommended_action",
    "recommendation_reason",
    "recency_days",
    "transactions_90d",
    "total_volume_90d",
    "failed_ratio_90d",
]


st.set_page_config(page_title="FX Retention Studio", layout="wide")


@st.cache_data
def load_csv(file_name: str) -> pd.DataFrame:
    path = CSV_DIR / file_name
    if not path.exists():
        raise FileNotFoundError(f"Missing required CSV: {path}")
    return pd.read_csv(path)


@st.cache_data
def load_dashboard_data() -> dict[str, pd.DataFrame]:
    return {
        "targeting": load_csv("user_repeat_targeting_dataset.csv"),
        "product_funnel": load_csv("product_funnel.csv"),
        "channel_funnel": load_csv("funnel_by_acquisition_channel.csv"),
        "d30_by_channel": load_csv("d30_repeat_by_channel.csv"),
        "feature_retention": load_csv("feature_combination_retention.csv"),
        "cohort_retention": load_csv("cohort_retention.csv"),
        "fx_behavior": load_csv("fx_regime_behavior.csv"),
        "fx_activity": load_csv("fx_regime_normalized_activity.csv"),
        "monthly_trend": load_csv("monthly_product_trend.csv"),
        "value_segments": load_csv("customer_value_segmentation.csv"),
        "modeling_check": load_csv("modeling_table_check.csv"),
        "metrics": load_csv("user_repeat_model_metrics.csv"),
        "importance": load_csv("user_repeat_feature_importance.csv"),
        "predictions": load_csv("user_repeat_predictions.csv"),
        "confusion": load_csv("user_repeat_confusion_matrix.csv"),
    }


def c(language: str, key: str):
    return COPY[language][key]


def kpi_text(language: str, key: str) -> tuple[str, str]:
    return COPY[language]["kpis"][key]


def page_title(language: str, page_key: str) -> str:
    if language == "English":
        return page_key
    return dict(zip(COPY["English"]["pages"], COPY["Korean"]["pages"]))[page_key]


def clean_label(value: str) -> str:
    return str(value).replace("_", " ").capitalize()


def format_number(value: float) -> str:
    if pd.isna(value):
        return "0"
    return f"{value:,.0f}"


def format_percent(value: float) -> str:
    if pd.isna(value):
        return "0.0%"
    return f"{value:.1f}%"


def format_krw(value: float) -> str:
    if pd.isna(value):
        return "KRW 0"
    if abs(value) >= 1_000_000_000:
        return f"KRW {value / 1_000_000_000:.1f}B"
    if abs(value) >= 1_000_000:
        return f"KRW {value / 1_000_000:.1f}M"
    return f"KRW {value:,.0f}"


def html_escape(value: str) -> str:
    return (
        str(value)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def inject_css() -> None:
    st.markdown(
        f"""
        <style>
        .stApp {{
            background: {COLOR_PAGE};
            color: {COLOR_TEXT};
        }}
        [data-testid="stHeader"] {{
            background: rgba(246, 248, 251, 0.92);
        }}
        .block-container {{
            padding-top: 1.4rem;
            padding-bottom: 3rem;
            max-width: 1480px;
        }}
        h1, h2, h3 {{
            color: {COLOR_TEXT};
            letter-spacing: 0;
        }}
        p, label, span {{
            letter-spacing: 0;
        }}
        [data-testid="stWidgetLabel"] p,
        [data-testid="stWidgetLabel"] label,
        [data-testid="stMarkdownContainer"] p,
        .stSlider label p,
        .stSelectbox label p,
        .stMultiSelect label p,
        .stTextInput label p,
        .stTextArea label p {{
            color: {COLOR_TEXT} !important;
            font-weight: 650;
        }}
        div[data-baseweb="select"] > div {{
            background-color: #FFFFFF !important;
            border-color: #CBD5E1 !important;
            color: {COLOR_TEXT} !important;
            box-shadow: none !important;
        }}
        div[data-baseweb="select"] span,
        div[data-baseweb="select"] input,
        div[data-baseweb="select"] svg {{
            color: {COLOR_TEXT} !important;
            fill: {COLOR_TEXT} !important;
        }}
        div[data-baseweb="popover"],
        div[data-baseweb="menu"] {{
            background-color: #FFFFFF !important;
            color: {COLOR_TEXT} !important;
        }}
        div[data-baseweb="menu"] li,
        div[data-baseweb="menu"] div {{
            color: {COLOR_TEXT} !important;
        }}
        div[data-baseweb="tag"] {{
            background-color: #EAF4F4 !important;
            border: 1px solid #B8DAD9 !important;
            color: {COLOR_TEXT} !important;
        }}
        div[data-baseweb="tag"] span,
        div[data-baseweb="tag"] svg {{
            color: {COLOR_TEXT} !important;
            fill: {COLOR_TEXT} !important;
        }}
        input, textarea {{
            background-color: #FFFFFF !important;
            color: {COLOR_TEXT} !important;
        }}
        .stSlider [data-baseweb="slider"] div {{
            color: {COLOR_TEXT} !important;
        }}
        .stSlider [role="slider"] {{
            background-color: {COLOR_TEAL} !important;
            border-color: {COLOR_TEAL} !important;
        }}
        .stButton button,
        .stDownloadButton button {{
            background-color: {COLOR_NAVY} !important;
            border: 1px solid {COLOR_NAVY} !important;
            color: #FFFFFF !important;
            border-radius: 8px !important;
            font-weight: 700 !important;
        }}
        .stButton button:disabled,
        .stDownloadButton button:disabled {{
            background-color: #E5E7EB !important;
            border-color: #E5E7EB !important;
            color: #98A2B3 !important;
        }}
        [data-testid="stDataFrame"] {{
            color: {COLOR_TEXT} !important;
        }}
        .hero {{
            border: 1px solid {COLOR_BORDER};
            border-radius: 12px;
            background: linear-gradient(135deg, #FFFFFF 0%, #ECF5F5 100%);
            padding: 24px 28px;
            margin-bottom: 18px;
        }}
        .hero h1 {{
            margin: 0 0 8px 0;
            font-size: 2.1rem;
            line-height: 1.08;
        }}
        .hero p {{
            margin: 0;
            color: {COLOR_MUTED};
            font-size: 1rem;
        }}
        .hero-chip {{
            display: inline-block;
            margin-top: 14px;
            padding: 7px 10px;
            border: 1px solid #C9D5DF;
            border-radius: 999px;
            background: #F8FAFC;
            color: #344054;
            font-size: 0.84rem;
            font-weight: 650;
        }}
        .metric-card {{
            min-height: 122px;
            border: 1px solid {COLOR_BORDER};
            border-radius: 10px;
            background: {COLOR_CARD};
            padding: 16px 16px 14px 16px;
            box-shadow: 0 1px 2px rgba(16, 24, 40, 0.04);
        }}
        .metric-label {{
            color: {COLOR_MUTED};
            font-size: 0.78rem;
            font-weight: 760;
            text-transform: uppercase;
            letter-spacing: 0.03em;
            margin-bottom: 8px;
            display: flex;
            align-items: center;
            gap: 6px;
        }}
        .info-icon {{
            display: inline-flex;
            align-items: center;
            justify-content: center;
            width: 16px;
            height: 16px;
            border-radius: 50%;
            border: 1px solid #B8C2CC;
            color: #667085;
            font-size: 11px;
            line-height: 16px;
            cursor: help;
            text-transform: none;
            letter-spacing: 0;
        }}
        .metric-value {{
            color: {COLOR_TEXT};
            font-size: 1.62rem;
            line-height: 1.15;
            font-weight: 780;
            margin-bottom: 6px;
        }}
        .metric-help {{
            color: {COLOR_MUTED};
            font-size: 0.82rem;
            line-height: 1.35;
        }}
        .section-title {{
            margin-top: 18px;
            margin-bottom: 4px;
            font-size: 1.28rem;
            font-weight: 780;
            color: {COLOR_TEXT};
        }}
        .section-subtitle {{
            margin-bottom: 14px;
            color: {COLOR_MUTED};
            font-size: 0.96rem;
        }}
        .insight-box, .action-box {{
            border: 1px solid {COLOR_BORDER};
            border-radius: 10px;
            background: {COLOR_CARD};
            padding: 15px 16px;
            min-height: 118px;
            box-shadow: 0 1px 2px rgba(16, 24, 40, 0.04);
        }}
        .insight-box {{
            border-left: 4px solid {COLOR_TEAL};
        }}
        .action-box {{
            border-left: 4px solid {COLOR_ORANGE};
        }}
        .box-kicker {{
            color: {COLOR_TEAL};
            font-size: 0.76rem;
            font-weight: 780;
            text-transform: uppercase;
            letter-spacing: 0.04em;
            margin-bottom: 6px;
        }}
        .box-title {{
            color: {COLOR_TEXT};
            font-size: 1.03rem;
            font-weight: 760;
            margin-bottom: 5px;
        }}
        .box-text {{
            color: {COLOR_MUTED};
            font-size: 0.92rem;
            line-height: 1.45;
        }}
        .rule-card {{
            border: 1px solid {COLOR_BORDER};
            border-radius: 10px;
            background: {COLOR_CARD};
            padding: 15px 16px;
            min-height: 132px;
            box-shadow: 0 1px 2px rgba(16, 24, 40, 0.04);
        }}
        .rule-card h3 {{
            margin-top: 0;
            margin-bottom: 8px;
            font-size: 1.02rem;
        }}
        .rule-card p {{
            color: {COLOR_MUTED};
            font-size: 0.92rem;
            line-height: 1.45;
        }}
        div[data-testid="stSidebar"] {{
            background: #FFFFFF;
            border-right: 1px solid {COLOR_BORDER};
        }}
        .small-note {{
            color: {COLOR_MUTED};
            font-size: 0.86rem;
            line-height: 1.4;
        }}
        </style>
        """,
        unsafe_allow_html=True,
    )


def render_header(language: str) -> None:
    st.markdown(
        f"""
        <div class="hero">
            <h1>FX Retention Studio</h1>
            <p>{html_escape(c(language, "app_subtitle"))}</p>
            <span class="hero-chip">{html_escape(c(language, "who_for"))}</span>
        </div>
        """,
        unsafe_allow_html=True,
    )


def section_header(language: str, page_key: str) -> None:
    st.markdown(
        f"""
        <div class="section-title">{html_escape(page_title(language, page_key))}</div>
        <div class="section-subtitle">{html_escape(COPY[language]["page_subtitles"][page_key])}</div>
        """,
        unsafe_allow_html=True,
    )


def metric_card(label: str, value: str, tooltip: str, caption: str = "") -> None:
    st.markdown(
        f"""
        <div class="metric-card">
            <div class="metric-label">
                <span>{html_escape(label)}</span>
                <span class="info-icon" title="{html_escape(tooltip)}">i</span>
            </div>
            <div class="metric-value">{html_escape(value)}</div>
            <div class="metric-help">{html_escape(caption)}</div>
        </div>
        """,
        unsafe_allow_html=True,
    )


def insight_box(kicker: str, title: str, text: str, action: bool = False) -> None:
    css_class = "action-box" if action else "insight-box"
    st.markdown(
        f"""
        <div class="{css_class}">
            <div class="box-kicker">{html_escape(kicker)}</div>
            <div class="box-title">{html_escape(title)}</div>
            <div class="box-text">{html_escape(text)}</div>
        </div>
        """,
        unsafe_allow_html=True,
    )


def style_plotly(fig: go.Figure, height: int = 430) -> go.Figure:
    fig.update_layout(
        height=height,
        margin=dict(l=20, r=20, t=58, b=42),
        paper_bgcolor="rgba(0,0,0,0)",
        plot_bgcolor="rgba(0,0,0,0)",
        font=dict(color=COLOR_TEXT, size=13),
        title=dict(font=dict(color=COLOR_TEXT, size=18), x=0),
        legend=dict(
            orientation="h",
            yanchor="bottom",
            y=1.03,
            xanchor="left",
            x=0,
            font=dict(color=COLOR_TEXT),
        ),
        hoverlabel=dict(bgcolor="white", font_size=12, font_color=COLOR_TEXT),
    )
    fig.update_xaxes(
        showgrid=False,
        linecolor=COLOR_BORDER,
        tickfont=dict(color=COLOR_TEXT),
        title_font=dict(color=COLOR_TEXT),
    )
    fig.update_yaxes(
        showgrid=True,
        gridcolor=COLOR_BORDER,
        zeroline=False,
        tickfont=dict(color=COLOR_TEXT),
        title_font=dict(color=COLOR_TEXT),
    )
    return fig


def to_csv_bytes(df: pd.DataFrame) -> bytes:
    return df.to_csv(index=False).encode("utf-8-sig")


def display_segment(language: str, segment: str) -> str:
    return COPY[language]["segments"].get(segment, segment)


def segment_options(language: str, targeting: pd.DataFrame) -> dict[str, str]:
    ordered = [
        "All users",
        "Low repeat probability users",
        "Medium repeat probability users",
        "High repeat probability users",
        "High-value at-risk users",
        "No recent transaction users",
        "High failed-ratio users",
    ]
    existing = ["All users"] + sorted(targeting["risk_segment"].dropna().unique().tolist())
    options = [segment for segment in ordered if segment in existing]
    extras = [segment for segment in existing if segment not in options]
    return {display_segment(language, segment): segment for segment in options + extras}


def select_targets(targeting: pd.DataFrame, segment: str, threshold: float) -> pd.DataFrame:
    selected = targeting.copy()
    if segment != "All users":
        selected = selected[selected["risk_segment"] == segment]
    selected = selected[selected["repeat_probability"] >= threshold]
    return selected.copy()


def target_summary(selected: pd.DataFrame) -> dict[str, float]:
    if selected.empty:
        return {
            "users": 0,
            "avg_probability": 0,
            "baseline_repeat_users": 0,
            "volume_90d": 0,
            "fee_proxy_90d": 0,
        }
    return {
        "users": len(selected),
        "avg_probability": selected["repeat_probability"].mean(),
        "baseline_repeat_users": selected["repeat_probability"].sum(),
        "volume_90d": selected["total_volume_90d"].sum(),
        "fee_proxy_90d": selected["estimated_fee_proxy_90d"].sum(),
    }


def business_view(df: pd.DataFrame) -> pd.DataFrame:
    cols = [
        "user_id",
        "observation_date",
        "repeat_probability",
        "risk_segment",
        "recommended_action",
        "recommendation_reason",
        "recency_days",
        "transactions_90d",
        "total_volume_90d",
        "failed_ratio_90d",
    ]
    view = df[cols].copy()
    view["repeat_probability"] = view["repeat_probability"].map(lambda x: f"{x:.1%}")
    view["failed_ratio_90d"] = view["failed_ratio_90d"].map(lambda x: f"{x:.1%}")
    view["total_volume_90d"] = view["total_volume_90d"].map(format_krw)
    return view.rename(columns=FIELD_LABELS)


def product_funnel_chart(df: pd.DataFrame) -> go.Figure:
    steps = [
        ("Valid signups", "valid_signups"),
        ("KYC completed", "kyc_completed"),
        ("Bank linked", "bank_linked"),
        ("First exchange", "first_successful_exchange"),
        ("Activated 14d", "activated_within_14_days"),
    ]
    chart_df = pd.DataFrame({"Step": [x[0] for x in steps], "Users": [df.loc[0, x[1]] for x in steps]})
    fig = px.bar(chart_df, x="Step", y="Users", text="Users", color_discrete_sequence=[COLOR_TEAL], title="Onboarding Funnel")
    fig.update_traces(texttemplate="%{text:,.0f}", textposition="outside", cliponaxis=False)
    fig.update_xaxes(title="")
    fig.update_yaxes(title="Users")
    return style_plotly(fig)


def monthly_signups_activation_chart(df: pd.DataFrame) -> go.Figure:
    chart_df = df.copy()
    chart_df["signup_month"] = pd.to_datetime(chart_df["signup_month"])
    fig = make_subplots(specs=[[{"secondary_y": True}]])
    fig.add_bar(x=chart_df["signup_month"], y=chart_df["valid_signups"], name="Valid signups", marker_color=COLOR_TEAL, secondary_y=False)
    fig.add_trace(
        go.Scatter(
            x=chart_df["signup_month"],
            y=chart_df["activation_rate_14d"],
            name="Activation rate",
            mode="lines+markers",
            line=dict(color=COLOR_ORANGE, width=3),
            marker=dict(size=8),
        ),
        secondary_y=True,
    )
    fig.update_layout(title="Monthly Signups and 14-Day Activation")
    fig.update_yaxes(title_text="Valid signups", secondary_y=False)
    fig.update_yaxes(title_text="Activation rate", ticksuffix="%", secondary_y=True)
    fig.update_xaxes(title="")
    return style_plotly(fig, height=450)


def horizontal_rate_chart(df: pd.DataFrame, label_col: str, value_col: str, title: str, color: str, height: int = 410) -> go.Figure:
    chart_df = df.copy().sort_values(value_col, ascending=True)
    fig = px.bar(chart_df, x=value_col, y=label_col, orientation="h", text=value_col, color_discrete_sequence=[color], title=title)
    fig.update_traces(texttemplate="%{text:.1f}%", textposition="outside", cliponaxis=False)
    fig.update_xaxes(title="", ticksuffix="%")
    fig.update_yaxes(title="")
    return style_plotly(fig, height=height)


def segment_mix_chart(df: pd.DataFrame) -> go.Figure:
    chart_df = df["risk_segment"].value_counts().rename_axis("Segment").reset_index(name="Users")
    fig = px.bar(chart_df, x="Users", y="Segment", orientation="h", text="Users", color_discrete_sequence=[COLOR_TEAL], title="Audience Segment Mix")
    fig.update_traces(texttemplate="%{text:,.0f}", textposition="outside", cliponaxis=False)
    fig.update_xaxes(title="Users")
    fig.update_yaxes(title="")
    return style_plotly(fig, height=390)


def recommendation_mix_chart(df: pd.DataFrame) -> go.Figure:
    chart_df = df["recommended_action"].value_counts().head(8).rename_axis("Action").reset_index(name="Users")
    fig = px.bar(chart_df, x="Users", y="Action", orientation="h", text="Users", color_discrete_sequence=[COLOR_NAVY], title="Top Recommended Actions")
    fig.update_traces(texttemplate="%{text:,.0f}", textposition="outside", cliponaxis=False)
    fig.update_xaxes(title="Users")
    fig.update_yaxes(title="")
    return style_plotly(fig, height=390)


def probability_distribution_chart(df: pd.DataFrame) -> go.Figure:
    fig = px.histogram(df, x="repeat_probability", nbins=30, color_discrete_sequence=[COLOR_TEAL], title="Repeat Likelihood Distribution")
    fig.update_xaxes(title="Repeat likelihood", tickformat=".0%")
    fig.update_yaxes(title="Users")
    return style_plotly(fig, height=390)


def cohort_heatmap(df: pd.DataFrame) -> go.Figure:
    chart_df = df[df["months_since_first_transaction"] > 0].copy()
    chart_df["cohort_month"] = pd.to_datetime(chart_df["cohort_month"]).dt.strftime("%Y-%m")
    pivot = chart_df.pivot(index="cohort_month", columns="months_since_first_transaction", values="retention_rate").sort_index()
    fig = px.imshow(
        pivot,
        aspect="auto",
        color_continuous_scale="Teal",
        text_auto=".1f",
        title="Cohort Retention Heatmap, M1-M6",
    )
    fig.update_xaxes(title="Months since first exchange")
    fig.update_yaxes(title="First exchange cohort")
    fig.update_coloraxes(colorbar_title="Retention %")
    return style_plotly(fig, height=460)


def fx_regime_chart(behavior: pd.DataFrame, activity: pd.DataFrame) -> go.Figure:
    chart_df = activity.merge(
        behavior[["market_regime_at_transaction", "success_rate"]],
        left_on="market_regime",
        right_on="market_regime_at_transaction",
        how="left",
    )
    chart_df["market_regime"] = pd.Categorical(chart_df["market_regime"], categories=["low", "normal", "high"], ordered=True)
    chart_df = chart_df.sort_values("market_regime")
    chart_df["Regime"] = chart_df["market_regime"].map(clean_label)
    fig = make_subplots(specs=[[{"secondary_y": True}]])
    fig.add_bar(
        x=chart_df["Regime"],
        y=chart_df["attempts_per_regime_hour"],
        text=chart_df["attempts_per_regime_hour"],
        texttemplate="%{text:.2f}",
        textposition="outside",
        name="Attempts per hour",
        marker_color=COLOR_TEAL,
        secondary_y=False,
    )
    fig.add_trace(
        go.Scatter(
            x=chart_df["Regime"],
            y=chart_df["success_rate"],
            mode="lines+markers",
            name="Success rate",
            line=dict(color=COLOR_ORANGE, width=3),
            marker=dict(size=9),
        ),
        secondary_y=True,
    )
    fig.update_layout(title="FX Regime Activity and Exchange Success")
    fig.update_yaxes(title_text="Attempts per regime hour", secondary_y=False)
    fig.update_yaxes(title_text="Success rate", ticksuffix="%", secondary_y=True)
    fig.update_xaxes(title="FX regime")
    return style_plotly(fig, height=430)


def value_segment_chart(df: pd.DataFrame) -> go.Figure:
    chart_df = df.copy()
    fig = go.Figure()
    fig.add_bar(
        x=chart_df["value_segment"],
        y=chart_df["target_rate_adoption_rate"],
        name="Target-rate adoption",
        marker_color=COLOR_NAVY,
    )
    fig.add_bar(
        x=chart_df["value_segment"],
        y=chart_df["rate_alert_adoption_rate"],
        name="Rate-alert adoption",
        marker_color=COLOR_TEAL,
    )
    fig.update_layout(title="Feature Adoption by Customer Value Segment", barmode="group")
    fig.update_xaxes(title="")
    fig.update_yaxes(title="Adoption rate", ticksuffix="%")
    return style_plotly(fig, height=420)


def metrics_chart(metrics: pd.DataFrame) -> go.Figure:
    long_df = metrics.melt(id_vars="model", value_vars=["accuracy", "precision", "recall", "f1", "roc_auc"], var_name="Metric", value_name="Score")
    fig = px.bar(long_df, x="model", y="Score", color="Metric", barmode="group", title="Prediction Quality by Model")
    fig.update_yaxes(range=[0, 1], tickformat=".0%")
    fig.update_xaxes(title="")
    return style_plotly(fig, height=430)


def feature_importance_chart(df: pd.DataFrame) -> go.Figure:
    chart_df = df.copy().sort_values("importance", ascending=True)
    chart_df["feature"] = chart_df["feature"].replace(
        {
            "transactions_90d": "Recent transactions",
            "total_volume_90d": "Recent volume",
            "recency_days": "Days since last transaction",
            "transactions_all": "Lifetime transactions",
            "failed_ratio_90d": "Recent failed transaction rate",
        }
    )
    fig = px.bar(chart_df, x="importance", y="feature", orientation="h", text="importance", color_discrete_sequence=[COLOR_TEAL], title="Top Prediction Signals")
    fig.update_traces(texttemplate="%{text:.2f}", textposition="outside", cliponaxis=False)
    fig.update_xaxes(title="Relative signal strength")
    fig.update_yaxes(title="")
    return style_plotly(fig, height=390)


def confusion_matrix_chart(confusion: pd.DataFrame) -> go.Figure:
    chart_df = confusion.copy()
    label_col = chart_df.columns[0]
    chart_df = chart_df.set_index(label_col)
    fig = px.imshow(
        chart_df.values,
        x=["Predicted no repeat", "Predicted repeat"],
        y=["Actual no repeat", "Actual repeat"],
        text_auto=True,
        color_continuous_scale="Blues",
        title="Where Predictions Were Right or Wrong",
    )
    fig.update_coloraxes(showscale=False)
    return style_plotly(fig, height=390)


def render_business_overview(language: str, data: dict[str, pd.DataFrame]) -> None:
    targeting = data["targeting"]
    section_header(language, "Business Overview")

    total_users = len(targeting)
    avg_repeat = targeting["repeat_probability"].mean()
    expected_repeat = targeting["repeat_probability"].sum()
    priority_mask = targeting["risk_segment"].isin(["High-value at-risk users", "High failed-ratio users", "Low repeat probability users"])
    priority_users = int(priority_mask.sum())

    cols = st.columns(4)
    labels = [
        ("users_scored", format_number(total_users), "Latest scored audience"),
        ("avg_repeat", format_percent(avg_repeat * 100), "Across all scored users"),
        ("expected_repeat", format_number(expected_repeat), "Before campaign action"),
        ("priority_users", format_number(priority_users), "Needs CRM attention"),
    ]
    for col, (key, value, caption) in zip(cols, labels):
        with col:
            label, tooltip = kpi_text(language, key)
            metric_card(label, value, tooltip, caption)

    left, right = st.columns(2)
    with left:
        st.plotly_chart(segment_mix_chart(targeting), width="stretch")
    with right:
        st.plotly_chart(recommendation_mix_chart(targeting), width="stretch")

    left, right = st.columns(2)
    with left:
        st.plotly_chart(monthly_signups_activation_chart(data["monthly_trend"]), width="stretch")
    with right:
        st.plotly_chart(probability_distribution_chart(targeting), width="stretch")

    insight_cols = st.columns(3)
    with insight_cols[0]:
        insight_box("What to watch", "Priority audience exists", "At-risk and reliability-sensitive users should be handled with targeted CRM actions instead of broad messages.")
    with insight_cols[1]:
        insight_box("Campaign opportunity", "Medium likelihood users are useful", "Users in the middle range often create the best practical audience for lifecycle nudges.")
    with insight_cols[2]:
        insight_box("Product signal", "Features support retention", "Rate alerts and target-rate orders are useful prompts, but should be tested with controlled campaigns.")


def render_product_performance(language: str, data: dict[str, pd.DataFrame]) -> None:
    section_header(language, "Product Performance")

    top = st.columns(2)
    with top[0]:
        st.plotly_chart(product_funnel_chart(data["product_funnel"]), width="stretch")
    with top[1]:
        st.plotly_chart(monthly_signups_activation_chart(data["monthly_trend"]), width="stretch")

    channel_df = data["channel_funnel"].copy()
    channel_df["channel_label"] = channel_df["acquisition_channel"].map(clean_label)
    feature_df = data["feature_retention"].copy()
    feature_df["feature_label"] = feature_df["feature_group"].map(clean_label)
    mid = st.columns(2)
    with mid[0]:
        st.plotly_chart(horizontal_rate_chart(channel_df, "channel_label", "activation_rate_14d", "Activation by Acquisition Channel", COLOR_TEAL), width="stretch")
    with mid[1]:
        st.plotly_chart(horizontal_rate_chart(feature_df, "feature_label", "d30_repeat_rate", "D30 Repeat by Feature Adoption", COLOR_NAVY), width="stretch")

    bottom = st.columns(2)
    with bottom[0]:
        st.plotly_chart(cohort_heatmap(data["cohort_retention"]), width="stretch")
    with bottom[1]:
        st.plotly_chart(fx_regime_chart(data["fx_behavior"], data["fx_activity"]), width="stretch")

    st.plotly_chart(value_segment_chart(data["value_segments"]), width="stretch")


def render_target_users(language: str, data: dict[str, pd.DataFrame]) -> None:
    targeting = data["targeting"]
    section_header(language, "Target Users")

    objective_map = COPY[language]["goals"]
    objective_display = st.selectbox("Campaign goal", list(objective_map.values()), help="Business outcome this campaign should support.")
    objective = {v: k for k, v in objective_map.items()}[objective_display]

    options = segment_options(language, targeting)
    col1, col2 = st.columns([1.3, 1])
    with col1:
        segment_display = st.selectbox("Audience segment", list(options.keys()), help=COPY[language]["segment_help"])
        segment = options[segment_display]
    with col2:
        threshold = st.slider("Minimum repeat likelihood", 0.0, 1.0, 0.35, 0.01, help=COPY[language]["threshold_help"])

    selected = select_targets(targeting, segment, threshold)
    summary = target_summary(selected)

    cols = st.columns(4)
    for col, (key, value, caption) in zip(
        cols,
        [
            ("target_audience", format_number(summary["users"]), "Users matching this setup"),
            ("avg_repeat", format_percent(summary["avg_probability"] * 100), "Average likelihood"),
            ("baseline_repeat", format_number(summary["baseline_repeat_users"]), "Expected repeats"),
            ("recent_volume", format_krw(summary["volume_90d"]), "Last 90 days"),
        ],
    ):
        with col:
            label, tooltip = kpi_text(language, key)
            metric_card(label, value, tooltip, caption)

    left, right = st.columns([1, 1])
    with left:
        insight_box("Recommended campaign", objective_display, COPY[language]["goal_actions"][objective], action=True)
        st.download_button(
            COPY[language]["download_targets"],
            data=to_csv_bytes(selected[BASE_EXPORT_FIELDS]),
            file_name="fx_retention_targets.csv",
            mime="text/csv",
            disabled=selected.empty,
        )
    with right:
        if selected.empty:
            st.warning(COPY[language]["empty_selection"])
        else:
            st.plotly_chart(segment_mix_chart(selected), width="stretch")

    st.dataframe(business_view(selected).head(500), width="stretch", hide_index=True)


def render_segment_explorer(language: str, data: dict[str, pd.DataFrame]) -> None:
    targeting = data["targeting"]
    section_header(language, "Segment Explorer")

    filters = st.columns(5)
    with filters[0]:
        probability_range = st.slider("Repeat likelihood", 0.0, 1.0, (0.0, 1.0), 0.01, help=kpi_text(language, "avg_repeat")[1])
    with filters[1]:
        recency_range = st.slider(
            "Days since last transaction",
            int(targeting["recency_days"].min()),
            int(targeting["recency_days"].max()),
            (int(targeting["recency_days"].min()), int(targeting["recency_days"].max())),
        )
    with filters[2]:
        tx_range = st.slider(
            "Recent transactions",
            int(targeting["transactions_90d"].min()),
            int(targeting["transactions_90d"].max()),
            (int(targeting["transactions_90d"].min()), int(targeting["transactions_90d"].max())),
        )
    with filters[3]:
        failed_range = st.slider(
            "Recent failed transaction rate",
            0.0,
            float(targeting["failed_ratio_90d"].max()),
            (0.0, float(targeting["failed_ratio_90d"].max())),
            0.01,
            help=kpi_text(language, "recent_failed_rate")[1],
        )
    with filters[4]:
        options = segment_options(language, targeting)
        segment_display = st.multiselect("Segment", list(options.keys()), default=list(options.keys()))
        selected_segments = [options[x] for x in segment_display]

    mask = (
        targeting["repeat_probability"].between(*probability_range)
        & targeting["recency_days"].between(*recency_range)
        & targeting["transactions_90d"].between(*tx_range)
        & targeting["failed_ratio_90d"].between(*failed_range)
    )
    if "All users" not in selected_segments:
        mask = mask & targeting["risk_segment"].isin(selected_segments)

    filtered = targeting[mask].copy()

    cols = st.columns(3)
    with cols[0]:
        label, tooltip = kpi_text(language, "target_audience")
        metric_card(label, format_number(len(filtered)), tooltip, "Filtered users")
    with cols[1]:
        label, tooltip = kpi_text(language, "avg_repeat")
        metric_card(label, format_percent(filtered["repeat_probability"].mean() * 100 if len(filtered) else 0), tooltip, "Filtered average")
    with cols[2]:
        label, tooltip = kpi_text(language, "expected_repeat")
        metric_card(label, format_number(filtered["repeat_probability"].sum()), tooltip, "Filtered baseline")

    st.download_button(
        COPY[language]["download_filtered"],
        data=to_csv_bytes(filtered[BASE_EXPORT_FIELDS]),
        file_name="fx_filtered_users.csv",
        mime="text/csv",
        disabled=filtered.empty,
    )
    st.dataframe(business_view(filtered).head(1000), width="stretch", hide_index=True)


def render_campaign_simulator(language: str, data: dict[str, pd.DataFrame]) -> None:
    targeting = data["targeting"]
    section_header(language, "Campaign Simulator")

    options = segment_options(language, targeting)
    col1, col2, col3 = st.columns(3)
    with col1:
        segment_display = st.selectbox("Audience segment", list(options.keys()), key="sim_segment", help=COPY[language]["segment_help"])
        segment = options[segment_display]
    with col2:
        threshold = st.slider("Minimum repeat likelihood", 0.0, 1.0, 0.35, 0.01, key="sim_threshold", help=COPY[language]["threshold_help"])
    with col3:
        uplift = st.slider("Expected campaign uplift", 0.0, 0.30, 0.05, 0.01, format="%.0f%%", help=COPY[language]["uplift_help"])

    selected = select_targets(targeting, segment, threshold)
    if selected.empty:
        st.warning(COPY[language]["empty_selection"])
        return

    baseline = selected["repeat_probability"].sum()
    after = np.minimum(selected["repeat_probability"] * (1 + uplift), 1).sum()
    incremental = after - baseline
    avg_volume = selected["total_volume_90d"].mean()
    incremental_volume = incremental * avg_volume
    fee_proxy = incremental_volume * FEE_RATE_PROXY

    cols = st.columns(5)
    values = [
        ("target_audience", format_number(len(selected)), "Campaign audience"),
        ("baseline_repeat", format_number(baseline), "Before campaign"),
        ("expected_repeat", format_number(after), "After campaign"),
        ("incremental_repeat", format_number(incremental), "Added users"),
        ("fee_proxy", format_krw(fee_proxy), "Simple fee proxy"),
    ]
    for col, (key, value, caption) in zip(cols, values):
        with col:
            label, tooltip = kpi_text(language, key)
            metric_card(label, value, tooltip, caption)

    scenario = pd.DataFrame({"Scenario": ["Before campaign", "After campaign"], "Expected repeat users": [baseline, after]})
    fig = px.bar(scenario, x="Scenario", y="Expected repeat users", text="Expected repeat users", color_discrete_sequence=[COLOR_TEAL], title="Campaign Impact Estimate")
    fig.update_traces(texttemplate="%{text:,.0f}", textposition="outside", cliponaxis=False)
    fig.update_yaxes(title="Expected repeat users")
    st.plotly_chart(style_plotly(fig), width="stretch")

    insight_box(
        "Planning note",
        f"{format_number(incremental)} incremental repeat users",
        f"At {format_percent(uplift * 100)} assumed uplift, this audience may add about {format_krw(incremental_volume)} in transaction volume.",
        action=True,
    )


def render_export_audience(language: str, data: dict[str, pd.DataFrame]) -> None:
    targeting = data["targeting"]
    section_header(language, "Export Audience")

    objective_map = COPY[language]["goals"]
    options = segment_options(language, targeting)
    col1, col2 = st.columns(2)
    with col1:
        campaign_name = st.text_input(COPY[language]["campaign_name"], value="FX repeat retention campaign")
        objective_display = st.selectbox("Campaign goal", list(objective_map.values()), key="export_goal")
        segment_display = st.selectbox("Audience segment", list(options.keys()), key="export_segment", help=COPY[language]["segment_help"])
        threshold = st.slider("Minimum repeat likelihood", 0.0, 1.0, 0.35, 0.01, key="export_threshold", help=COPY[language]["threshold_help"])
    with col2:
        available_fields = list(FIELD_LABELS.keys())
        selected_fields = st.multiselect(
            COPY[language]["selected_fields"],
            available_fields,
            default=BASE_EXPORT_FIELDS,
            format_func=lambda x: FIELD_LABELS.get(x, x),
        )
        notes = st.text_area(COPY[language]["campaign_notes"], value="Audience selected from FX Retention Studio.")

    selected = select_targets(targeting, options[segment_display], threshold)
    export_df = selected[selected_fields].copy()
    export_df.insert(0, "campaign_name", campaign_name)
    export_df.insert(1, "campaign_goal", objective_display)
    export_df.insert(2, "campaign_notes", notes)

    cols = st.columns(3)
    with cols[0]:
        label, tooltip = kpi_text(language, "target_audience")
        metric_card(label, format_number(len(export_df)), tooltip, "Rows in export")
    with cols[1]:
        label, tooltip = kpi_text(language, "baseline_repeat")
        metric_card(label, format_number(selected["repeat_probability"].sum()), tooltip, "Expected repeats")
    with cols[2]:
        label, tooltip = kpi_text(language, "recent_volume")
        metric_card(label, format_krw(selected["total_volume_90d"].sum()), tooltip, "Recent audience volume")

    st.download_button(
        COPY[language]["download_export"],
        data=to_csv_bytes(export_df),
        file_name="fx_crm_audience_export.csv",
        mime="text/csv",
        disabled=export_df.empty,
    )
    st.dataframe(export_df.head(500), width="stretch", hide_index=True)


def render_prediction_quality(language: str, data: dict[str, pd.DataFrame]) -> None:
    section_header(language, "Prediction Quality")
    insight_box("Plain English", "Where the model appears in the product", COPY[language]["prediction_plain"])

    metrics = data["metrics"].copy()
    best = metrics.sort_values("roc_auc", ascending=False).iloc[0]
    cols = st.columns(4)
    model_cards = [
        ("Best model", str(best["model"]), "Model selected by strongest ROC-AUC in the current comparison."),
        ("ROC-AUC", format_percent(best["roc_auc"] * 100), "Ability to rank repeat users above non-repeat users."),
        ("F1 score", format_percent(best["f1"] * 100), "Balance between precision and recall."),
        ("Recall", format_percent(best["recall"] * 100), "Share of actual repeat users the model identified."),
    ]
    for col, (label, value, tooltip) in zip(cols, model_cards):
        with col:
            metric_card(label, value, tooltip, "Latest test period")

    left, right = st.columns(2)
    with left:
        st.plotly_chart(metrics_chart(metrics), width="stretch")
    with right:
        st.plotly_chart(feature_importance_chart(data["importance"]), width="stretch")

    left, right = st.columns(2)
    with left:
        st.plotly_chart(confusion_matrix_chart(data["confusion"]), width="stretch")
    with right:
        st.plotly_chart(probability_distribution_chart(data["targeting"]), width="stretch")

    modeling = data["modeling_check"]
    st.markdown("#### Data quality summary")
    st.dataframe(modeling, width="stretch", hide_index=True)
    st.caption("This portfolio uses synthetic product data. The app demonstrates analytics and product decision workflow, not production deployment readiness.")


def main() -> None:
    inject_css()
    data = load_dashboard_data()

    with st.sidebar:
        language = st.radio("Language / 언어", ["English", "Korean"], horizontal=True)
        selected_page = st.radio(c(language, "nav"), c(language, "pages"))
        st.markdown("---")
        st.caption("FX Retention Studio")
        st.caption(c(language, "app_subtitle"))

    page_key = PAGE_KEYS[selected_page]
    render_header(language)

    if page_key == "Business Overview":
        render_business_overview(language, data)
    elif page_key == "Product Performance":
        render_product_performance(language, data)
    elif page_key == "Target Users":
        render_target_users(language, data)
    elif page_key == "Segment Explorer":
        render_segment_explorer(language, data)
    elif page_key == "Campaign Simulator":
        render_campaign_simulator(language, data)
    elif page_key == "Export Audience":
        render_export_audience(language, data)
    elif page_key == "Prediction Quality":
        render_prediction_quality(language, data)


if __name__ == "__main__":
    main()
